[printer Replicator02]
titlebar_items: chamber

[main]
screen_on_devices: Auto Lights
screen_off_devices: Auto Lights

[menu __main custom]
name: Prepare
icon: klipper

[menu __main custom present]
name: Present Toolhead
icon: bed-level-t-r
method: printer.gcode.script
params: {"script":"present_toolhead"}

[menu __main custom load]
name: Load Clean
icon: arrow-down
method: printer.gcode.script
params: {"script":"load_clean"}

[menu __main custom unload]
name: Unload Clean
icon: arrow-up
method: printer.gcode.script
params: {"script":"unload_clean"}

[menu __main custom stow]
name: Stow Toolhead
icon: bed-level-b-l
method: printer.gcode.script
params: {"script":"stow_toolhead"}

[menu __main custom ready_up_pla]
name: Ready Up PLA
icon: filament
method: printer.gcode.script
params: {"script":"ready_up_pla"}

[menu __main custom ready_up_asa]
name: Ready Up ASA
icon: filament
method: printer.gcode.script
params: {"script":"ready_up_asa"}

[menu __main custom ready_up_petg]
name: Ready Up PETG
icon: filament
method: printer.gcode.script
params: {"script":"ready_up_petg"}

[menu __main custom ready_up_tpu]
name: Ready Up TPU
icon: filament
method: printer.gcode.script
params: {"script":"ready_up_tpu"}

[menu __main custom clean]
name: Nozzle Clean
icon: shuffle
method: printer.gcode.script
params: {"script":"clean_nozzle"}

[menu __main custom machine_level]
name: Machine Level
icon: z-tilt
method: printer.gcode.script
params: {"script":"machine_level_cold"}

[menu __main custom z_ascender]
name: Z Ascender
icon: warning
method: printer.gcode.script
params: {"script":"z_ascender"}

[menu __main custom heatsoak_toggle]
name: Heatsoak Toggle
icon: heat-up
method: printer.gcode.script
params: {"script":"HEATSOAK_TOGGLE"}

[menu __main custom reset_file]
name: Reset Print State
icon: sd
method: printer.gcode.script
params: {"script":"_RESET_FILE_STATE"}

[menu __main custom cleaner_recogniser]
name: Cleaner Recogniser
icon: shuffle
method: printer.gcode.script
params: {"script":"DEMON_CLEANER_PAD_RECOGNISER"}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-dark
#~# screen_blanking = 14400
#~# screen_blanking_printing = off
#~# font_size = small
#~# only_heaters = True
#~# show_heater_power = True
#~# show_scroll_steppers = True
#~# print_sort_dir = date_desc
#~#
